' Cálculo dos juros, sendo que precisa de arrays para isso
' Versao 0.1: 08/04/2026: feito sem muito conhecimento de pybasic

' variáveis globais para simplificar os processos e inicialização das escalares
QUANTIDADE = 3
COMPOSTO = 1  ' 1 = TRUE
PERIODO = 30
DIM PAGAMENTOS(QUANTIDADE) AS DECIMAL
DIM PESOS(QUANTIDADE) AS DECIMAL

' calcula a somatória dos elementos do array PESOS()
FUNCTION GETPESOTOTAL()
    ACUMULADOR = 0

    FOR INDICE = 1 TO QUANTIDADE
        ACUMULADOR = ACUMULADOR + PESOS(INDICE)
    NEXT INDICE

    RETURN ACUMULADOR
END FUNCTION

' calcula o acréscimo a partir dos juros e parcelas
FUNCTION JUROSPARAACRESCIMO(JUROS)
    PESOTOTAL = GETPESOTOTAL()
    IF QUANTIDADE < 1 OR PERIODO <= 0 OR PESOTOTAL <= 0 OR JUROS <= 0 THEN
        RETURN 0
    END IF
    ACUMULADOR = 0

    FOR INDICE = 1 TO QUANTIDADE
        IF COMPOSTO = 1 THEN
            ACUMULADOR = ACUMULADOR + PESOS(INDICE) / (1 + JUROS / 100) ^ (PAGAMENTOS(INDICE) / PERIODO)
        ELSE
            ACUMULADOR = ACUMULADOR + PESOS(INDICE) / (1 + JUROS / 100 * PAGAMENTOS(INDICE) / PERIODO)
        END IF
    NEXT INDICE

    IF ACUMULADOR <= 0 THEN
        RETURN 0
    END IF
    RETURN (PESOTOTAL / ACUMULADOR - 1) * 100
END FUNCTION

' calcula os juros a partir do acréscimo e parcelas
FUNCTION ACRESCIMOPARAJUROS(ACRESCIMO, PRECISAO, MAXITERACOES, MAXJUROS)
    PESOTOTAL = GETPESOTOTAL()
    IF QUANTIDADE < 1 OR PERIODO <= 0 OR PESOTOTAL <= 0 OR ACRESCIMO <= 0 OR PRECISAO < 1 OR MAXITERACOES < 1 OR MAXJUROS <= 0 THEN
        RETURN 0
    END IF
    MINJUROS = 0
    MEDJUROS = MAXJUROS / 2
    MINDIFERENCA = 0.1 ^ PRECISAO

    FOR ITERACAO = 1 TO MAXITERACOES
        IF MAXJUROS - MINJUROS < MINDIFERENCA THEN
            RETURN MEDJUROS
        END IF
        IF JUROSPARAACRESCIMO(MEDJUROS) < ACRESCIMO THEN
            MINJUROS = MEDJUROS
        ELSE
            MAXJUROS = MEDJUROS
        END IF
        MEDJUROS = (MINJUROS + MAXJUROS) / 2
    NEXT ITERACAO
    
    RETURN MEDJUROS
END FUNCTION

' inicializa os elementos dos arrays PAGAMENTOS() e PESOS()
FOR INDICE = 1 TO QUANTIDADE
    PAGAMENTOS(INDICE) = INDICE * PERIODO
    PESOS(INDICE) = 1
NEXT INDICE

' calcula e guarda os resultados das funções
PESOTOTAL = GETPESOTOTAL()
ACRESCIMOCALCULADO = JUROSPARAACRESCIMO(3)
JUROSCALCULADO = ACRESCIMOPARAJUROS(ACRESCIMOCALCULADO, 15, 65, 50)

' imprime os resultados
PRINT "Peso total = " + PESOTOTAL
PRINT "Acréscimo = " + ACRESCIMOCALCULADO
PRINT "Juros = " + JUROSCALCULADO
